//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARCENTRdb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class АвтосалонEntities1 : DbContext
    {
        public АвтосалонEntities1()
            : base("name=АвтосалонEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<История> История { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Комплектация> Комплектация { get; set; }
        public virtual DbSet<Марка> Марка { get; set; }
        public virtual DbSet<Модель> Модель { get; set; }
        public virtual DbSet<Паспорт> Паспорт { get; set; }
        public virtual DbSet<Сделка> Сделка { get; set; }
        public virtual DbSet<Состояние> Состояние { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Способ_оплаты> Способ_оплаты { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
        public virtual DbSet<Финансовые_операции> Финансовые_операции { get; set; }
        public virtual DbSet<Цвет> Цвет { get; set; }
    }
}
