//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARCENTRdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сделка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сделка()
        {
            this.Финансовые_операции = new HashSet<Финансовые_операции>();
        }
    
        public int Код_сделки { get; set; }
        public int Код_сотрудника { get; set; }
        public int Код_клиента { get; set; }
        public System.DateTime Дата_сделки { get; set; }
        public decimal Сумма_сделки { get; set; }
        public int Код_Способ_оплаты { get; set; }
        public int Срок_гарантии { get; set; }
        public int Код_авто { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Способ_оплаты Способ_оплаты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Финансовые_операции> Финансовые_операции { get; set; }
    }
}
