//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARCENTRdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Финансовые_операции
    {
        public int Код_операции { get; set; }
        public int Код_сделки { get; set; }
        public decimal Сумма { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual Сделка Сделка { get; set; }
    }
}
